### ISSUE TITLE
Site history table

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#165]
## Detailed Description
It would be good to store the history of site changes. 

## Context
- good to know who changes the sites

## Possible Implementation
- create site history table
- same fields as site 
- extra field: user_uuid, the user who updated it
- extra field: update_from_site_historic_uuid, a link to the last update of site parameters
- link this table to the sites table
- have function that 1. updates site, 2. add new enter to site history table.

**Comment by mduffin95** [comment]
I can take a look at this

**Comment by mduffin95** [comment]
How will the history table be used?

I ask because an alternative approach would be to use triggers to store the old record in a `JSONB` column every time the `sites` table is updated. This has the advantage of being easier to migrate over time as it doesn't use such a rigid schema. However that schema might be required if we want to query the data. 

Do you think this approach would be sufficient?

**Comment by peterdudfield** [comment]
Hey, 

Yea idea with the json column. Thats definitely something we could do. 

We will likely not query it that much, apart from looking at the history of one site. And see the 5 to 10 updates its had. I dont think it'll be thousands. I like the idea, means if the site table schema changes, then we would not have to worry about destroying the history table. 

So perhaps the columns would be 
- site_historic_uuid 
- site_uuid
- json field with all params
- update_from_site_historic_uuid, a link to the last update of site parameters
- user_uuid, the user who updated it
but i'm open to ideas....

**Comment by mduffin95** [comment]
@peterdudfield added an initial preparatory PR.

**Comment by mduffin95** [comment]
@peterdudfield main PR is up

**Comment by peterdudfield** [comment]
Tested on India development database - it worked.
